In [1]:
import numpy as np

In [2]:
x = np.arange(0,21)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
full = np.full(10,3.14)
full

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [6]:
arr = np.arange(0,100,4)
arr


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [7]:
arr = np.arange(10).reshape(5,2)
arr


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
ls = list(range(0,100))      
l1= [x for x in range(0,10)]  
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
l3 = [str(x) for x in l1]      
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
powerr = [x**2 for x in l1]       
powerr

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [11]:
import array as a
ar = a.array('i',l1)
ar_pow = a.array('i',[x**2 for x in l1])
ar_pow

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [12]:
np_arr = np.array([x+3 for x in l1])
np_arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
np_arr1 = np.array([x for x in l1],dtype=float) 
np_arr1 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
z = np.float64([x for x in l1])
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
l2d = [range(i,i+4) for i in [1,4,5]]
np.array(l2d)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [16]:
np.zeros([4,4],dtype=int) 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [19]:
arrr = np.zeros((10,10))
arrr[1:-1,1:-1]=1
arrr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
arrr[1:9,1:9]=1
arrr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
arr = np.full((3,3),3.147)
arr

array([[3.147, 3.147, 3.147],
       [3.147, 3.147, 3.147],
       [3.147, 3.147, 3.147]])

In [22]:
arr = np.ones((3,3))
arr[:]=3.147
arr

array([[3.147, 3.147, 3.147],
       [3.147, 3.147, 3.147],
       [3.147, 3.147, 3.147]])

In [23]:
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [24]:
x_t = np.matrix.transpose(x)
x_t

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [25]:
ff = np.full((6,6),64)
ff

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [26]:
np.linspace(0,1,10) 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [27]:
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [28]:
np.random.random((3,3))

array([[0.9860178 , 0.14301608, 0.30602616],
       [0.95633878, 0.21879442, 0.82224267],
       [0.23501373, 0.1850756 , 0.85790776]])

In [29]:
np.random.normal(1,4,(1,10))

array([[ 0.68780452,  2.69634253,  8.61162626,  3.18784173, -0.56229238,
         5.29268514,  2.10583519, -1.78140751, -5.88214098, -0.33672237]])

In [30]:
np.random.normal(0,1,(4,5))

array([[-0.50559008, -0.35307209, -0.22322973,  0.45758472, -0.2885002 ],
       [-0.52912043,  0.98218906, -0.06292456,  1.2279198 ,  0.72318308],
       [-0.34729448, -0.04513103,  1.02681131,  2.04947499, -0.17689002],
       [-0.09034271, -0.37105837,  2.89042988,  1.24051367,  1.41139208]])

In [31]:
np.random.randint(50,100,30)

array([66, 91, 78, 52, 78, 67, 86, 74, 83, 89, 72, 85, 57, 78, 89, 50, 64,
       81, 54, 62, 67, 73, 69, 78, 63, 99, 67, 74, 93, 58])

In [32]:
ar = np.random.randint(10,101,(20,2))
ar

array([[98, 44],
       [17, 17],
       [82, 92],
       [64, 14],
       [19, 12],
       [38, 87],
       [59, 80],
       [62, 10],
       [65, 82],
       [10, 43],
       [15, 24],
       [83, 32],
       [11, 50],
       [84, 26],
       [97, 79],
       [81, 71],
       [61, 80],
       [55, 85],
       [92, 84],
       [90, 35]])

In [33]:
ar.ndim 

2

In [34]:
ar.size 

40

In [35]:
ar.shape 

(20, 2)

In [36]:
ar.dtype 

dtype('int32')

In [37]:
np.random.seed(101)
ar = np.random.randint(1,10,10)
ar

array([2, 7, 8, 9, 5, 9, 6, 1, 6, 9])

In [38]:
ar[:4]

array([2, 7, 8, 9])

In [39]:
ar[-1]

9

In [40]:
ar[5]

9

In [41]:
ar[1]=45
ar

array([ 2, 45,  8,  9,  5,  9,  6,  1,  6,  9])

In [42]:
np.random.seed(100)
arrx= np.arange(1,101).reshape(10,10)
arrx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [43]:
arrx[0:3,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23]])

In [44]:
arrx[0,1]

2

In [45]:
arrx[0:3,1]

array([ 2, 12, 22])

In [46]:
arrx[:3,:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [47]:
arrx[2::-1,3::-1]

array([[24, 23, 22, 21],
       [14, 13, 12, 11],
       [ 4,  3,  2,  1]])

In [48]:
arrx[2:,3:]

array([[ 24,  25,  26,  27,  28,  29,  30],
       [ 34,  35,  36,  37,  38,  39,  40],
       [ 44,  45,  46,  47,  48,  49,  50],
       [ 54,  55,  56,  57,  58,  59,  60],
       [ 64,  65,  66,  67,  68,  69,  70],
       [ 74,  75,  76,  77,  78,  79,  80],
       [ 84,  85,  86,  87,  88,  89,  90],
       [ 94,  95,  96,  97,  98,  99, 100]])

In [49]:
arrx[2::2,3::2]

array([[24, 26, 28, 30],
       [44, 46, 48, 50],
       [64, 66, 68, 70],
       [84, 86, 88, 90]])

In [50]:
arrx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [51]:
arx = arrx[2:5,2:5]
arx

array([[23, 24, 25],
       [33, 34, 35],
       [43, 44, 45]])

In [52]:
arx[2,2]=122
arx

array([[ 23,  24,  25],
       [ 33,  34,  35],
       [ 43,  44, 122]])

In [53]:
arrx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44, 122,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [54]:
ar1 = arrx[2:5,2:5].copy()
ar1

array([[ 23,  24,  25],
       [ 33,  34,  35],
       [ 43,  44, 122]])

In [55]:
ar1[2,2]=24
ar1

array([[23, 24, 25],
       [33, 34, 35],
       [43, 44, 24]])

In [56]:
arrx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44, 122,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [57]:
arrrr = np.arange(3)
arrrr.reshape(3,1)


array([[0],
       [1],
       [2]])

In [58]:
arrrr = np.arange(16)
reshape = arrrr.reshape(4,4)  
reshape.reshape(1,16)   

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [59]:
flatten = arrr.flatten()

In [60]:
flatten[:,np.newaxis]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [61]:
np.concatenate([arx,ar1])  

array([[ 23,  24,  25],
       [ 33,  34,  35],
       [ 43,  44, 122],
       [ 23,  24,  25],
       [ 33,  34,  35],
       [ 43,  44,  24]])

In [62]:
np.concatenate([arx,ar1],axis=1)  

array([[ 23,  24,  25,  23,  24,  25],
       [ 33,  34,  35,  33,  34,  35],
       [ 43,  44, 122,  43,  44,  24]])

In [63]:
arz=np.array([1,2,3,4,5,6]).reshape(2,3)
arz

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
ara=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
ara

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
np.concatenate([arz,ara],axis=1)

array([[1, 2, 3, 1, 2, 3, 4],
       [4, 5, 6, 5, 6, 7, 8]])

In [66]:
x=np.array([[1,2,3],[4,5,6]])
arrrrr = np.array([7,8,9])
ar_1 = np.array([[1,2],[3,4]])
ar_2 = np.array((1,2,3,4,5))

In [67]:
np.vstack([x,arrrrr])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.vstack([arrrrr,x])

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.hstack([x,ar_1])

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])

In [70]:
x
ar89 = np.array((1,2,3,4,5,6))

In [71]:
np.split(ar_2,(1,4,5),axis=0) 

[array([1]), array([2, 3, 4]), array([5]), array([], dtype=int32)]

In [72]:
np.vsplit(x,[1,2])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

In [73]:
np.hsplit(x,[2,2])
# it return [:1],[1:2],[2:]

[array([[1, 2],
        [4, 5]]),
 array([], shape=(2, 0), dtype=int32),
 array([[3],
        [6]])]

In [75]:
ar2d = np.array([[1,2,3],[-4,5,6],[7,-8,9]])
np.sum(ar2d)

21

In [76]:
np.sum(ar2d,axis=1)

array([6, 7, 8])

In [77]:
np.sum(ar2d,axis=0)

array([ 4, -1, 18])

In [78]:
np.std(ar2d)

5.120763831912405

In [79]:
np.prod(ar2d)

362880

In [80]:
np.var(ar2d)

26.222222222222218

In [81]:
np.abs(ar2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.argmax(ar2d)

8

In [83]:
np.argmin(ar2d)

7

In [84]:
np.argmax(ar2d,axis=0)

array([2, 1, 2], dtype=int64)

In [85]:
np.argmin(ar2d,axis=0)

array([1, 2, 0], dtype=int64)

In [86]:
np.argmax(ar2d,axis=1)

array([2, 2, 2], dtype=int64)

In [91]:
np.argmin(ar2d,axis=1)

array([0, 0, 1], dtype=int64)

In [92]:
np.median(ar2d)

3.0

In [93]:
# np.all?
np.all(ar2d,axis=0)

array([ True,  True,  True])

In [94]:
ar1=np.array([1,2,3,4,7])
ar1

array([1, 2, 3, 4, 7])

In [95]:
ar1>2

array([False, False,  True,  True,  True])

In [96]:
ar1==2

array([False,  True, False, False, False])

In [97]:
ar1<6

array([ True,  True,  True,  True, False])

In [98]:
ar1!=9

array([ True,  True,  True,  True,  True])

## Exersise

In [99]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [100]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [101]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [102]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [103]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
x=np.eye(3,3)
x
np.all(x)

False

In [105]:
np.random.randint(0,2,1)


array([0])

In [106]:
np.random.standard_normal(25)


array([-0.89325872,  1.7382604 , -1.17970327,  0.08857118, -0.36377559,
       -0.39830003, -0.23471518, -1.43973704,  0.4328165 ,  2.30447259,
       -0.12263538,  0.01545931,  0.26601635, -0.11379467,  1.01106614,
       -1.44077118,  0.98056914,  1.37699631, -0.23028509,  0.48092412,
       -1.26691058,  0.27100509,  2.14076322,  0.47536904,  0.24652489])

In [107]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [108]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [109]:
ar = np.array([[ 1,  2,  3,  4,  5], 
       [ 6,  7,  8,  9, 10], 
       [11, 12, 13, 14, 15], 
       [16, 17, 18, 19, 20], 
       [21, 22, 23, 24, 25]]) 
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [110]:

ar[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [111]:
ar[3:4,-1]

array([20])

In [112]:
ar[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [113]:
ar[4]

array([21, 22, 23, 24, 25])

In [114]:
ar[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [115]:
np.sum(ar)

325

In [116]:
np.sum(ar,axis=0)

array([55, 60, 65, 70, 75])

In [117]:
np.std(ar,axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [118]:
np.var(ar,axis=1)

array([2., 2., 2., 2., 2.])

In [119]:
np.min(ar,axis=1)

array([ 1,  6, 11, 16, 21])

In [120]:
np.max(ar,axis=1)

array([ 5, 10, 15, 20, 25])

In [121]:
a = np.full((6,6),np.nan)
a[1:5,1:5]=1
a


array([[nan, nan, nan, nan, nan, nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan, nan, nan, nan, nan, nan]])

In [122]:
ar1=np.array([2,3,4,5])
ar1

array([2, 3, 4, 5])

In [123]:
np.random.seed(1)
ar2=np.arange(0,9).reshape(3,3)
ar2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
np.random.seed(2)
ar3=np.arange(0,27).reshape(3,3,3)
ar3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [125]:
ar3.dtype

dtype('int32')

In [126]:
ar1.shape 

(4,)

In [127]:
ar2.shape

(3, 3)

In [128]:
ar3.shape

(3, 3, 3)

In [129]:
ar1.ndim

1

In [130]:
ar2.ndim

2

In [131]:
ar3.ndim

3

In [132]:
ar4 = np.zeros(12)
ar4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [133]:
ar5 = np.ones((2,10))
ar5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [134]:
np.random.seed(102)
Maths_Marks = np.random.randint(0,100,20)
Maths_Marks

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7,  4, 38, 82, 55,  3, 96,  0,
       80, 71, 25])

In [135]:
desc = np.sort(Maths_Marks)[::-1]  
desc

array([96, 82, 80, 79, 78, 73, 73, 72, 72, 71, 66, 55, 45, 38, 25,  7,  4,
        3,  0,  0])

In [136]:
asc = np.sort(Maths_Marks)  
asc

array([ 0,  0,  3,  4,  7, 25, 38, 45, 55, 66, 71, 72, 72, 73, 73, 78, 79,
       80, 82, 96])

In [137]:
copy_dsc = np.copy(desc)
copy_dsc

array([96, 82, 80, 79, 78, 73, 73, 72, 72, 71, 66, 55, 45, 38, 25,  7,  4,
        3,  0,  0])

In [138]:
ar10001 = np.eye(5,5)

In [139]:
np.reshape(ar10001,(1,25))

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1.]])

In [140]:
np.random.seed(10000)
ar201 = np.random.randint(0,9,9).reshape(3,3)
ar201


array([[5, 8, 2],
       [5, 8, 1],
       [6, 8, 5]])

In [141]:
np.random.seed(10001)
ar202 = np.random.randint(0,9,3)
ar202

array([1, 4, 6])

In [142]:
ar301 = np.vstack((ar201,ar202))
ar301

array([[5, 8, 2],
       [5, 8, 1],
       [6, 8, 5],
       [1, 4, 6]])

In [143]:

np.vsplit(ar301,[2,3])


[array([[5, 8, 2],
        [5, 8, 1]]),
 array([[6, 8, 5]]),
 array([[1, 4, 6]])]

In [144]:
np.hsplit(ar301,[1,2])

[array([[5],
        [5],
        [6],
        [1]]),
 array([[8],
        [8],
        [8],
        [4]]),
 array([[2],
        [1],
        [5],
        [6]])]

In [145]:
np.eye(4,4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [146]:
ar302 = np.array([1.2,6.5,8.0,7.7,3.4,1.9])
np.ceil(ar302)

array([2., 7., 8., 8., 4., 2.])

In [147]:
np.floor(ar302)

array([1., 6., 8., 7., 3., 1.])

In [148]:
np.round(ar302)

array([1., 6., 8., 8., 3., 2.])

In [149]:
ar303 = np.arange(3,28).reshape(5,5)

In [150]:
np.min(ar303,axis=0)

array([3, 4, 5, 6, 7])

In [151]:
np.max(ar303,axis=0)

array([23, 24, 25, 26, 27])

In [152]:
np.var(ar303,axis=0)

array([50., 50., 50., 50., 50.])

In [153]:
np.std(ar303,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [154]:
nv = np.full(10,np.nan)
nv[6]=200
nv


array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [155]:
vec1 = np.arange(100,151)
vec1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [156]:
vec1[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [157]:
np.arange(0,25).reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [158]:
ar403 = np.array([1,0,2,0,0,4,0,8])
np.nonzero(ar403)[0]

array([0, 2, 5, 7], dtype=int64)

In [159]:
ar404 = np.full(100,1).reshape(10,10)
ar404[1:9,1:9]=0
ar404

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [160]:
mat1 = np.ones((9,9))
mat1[::2,::2]=0
mat1[1::,1::2]=0
mat1

array([[0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [161]:
np.random.seed(102)
arx = np.random.randint(0,9,9).reshape(3,3)
arx

array([[0, 3, 2],
       [2, 2, 8],
       [8, 7, 4]])

In [162]:
np.random.seed(20001)
ary = np.random.randint(20,50,9).reshape(3,3)
ary

array([[25, 29, 26],
       [43, 25, 29],
       [31, 41, 43]])

In [163]:
np.sum((arx,ary),axis=0)

array([[25, 32, 28],
       [45, 27, 37],
       [39, 48, 47]])

In [164]:
np.multiply(arx,ary)

array([[  0,  87,  52],
       [ 86,  50, 232],
       [248, 287, 172]])

In [165]:
np.subtract(ary,arx)

array([[25, 26, 24],
       [41, 23, 21],
       [23, 34, 39]])