In [1]:
import numpy as np

In [2]:
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
arr3 = np.full(10,3.14)
arr3

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [6]:
arr = np.arange(0,50,4)
arr


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [7]:
arr = np.arange(0,9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
lst = list(range(0,10))      
l2 = [x for x in range(0,10)]  
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
l3 = [str(x) for x in l2]      
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
l4 = [x**2 for x in l2]       
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

## Array Library

In [11]:
import array as a
ar = a.array('i',l2)
ar1 = a.array('i',[x**2 for x in l2])
ar1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [12]:
nparr = np.array([x+3 for x in l2])
nparr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
nparr1 = np.array([x for x in l2],dtype=float) 
nparr1 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
nparr2 = np.float64([x for x in l2])
nparr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
l2d = [range(i,i+4) for i in [1,4,5]]
np.array(l2d)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [16]:
np.zeros([2,2],dtype=int) 

array([[0, 0],
       [0, 0]])

In [17]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [19]:
nparr3 = np.zeros((10,10))
nparr3[1:-1,1:-1]=1

nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
nparr3[1:9,1:9]=1
nparr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
arr = np.full((3,3),3.14)
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [22]:
arr = np.ones((3,3))
arr[:]=3.14
arr

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [23]:
arr5 = np.eye(7)
arr5

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [24]:
arr7 = np.matrix.transpose(arr5)
arr7

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [25]:
arr8 = np.full((6,6),64)
arr8

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [26]:
np.linspace(0,1,5) 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [28]:
np.random.random((3,3))

array([[0.08061821, 0.33630616, 0.95417369],
       [0.51255738, 0.91117685, 0.53797067],
       [0.90136496, 0.37752816, 0.673101  ]])

In [199]:
np.random.normal(1,4,(1,10))

array([[-0.48711128, -0.19995793,  3.18734967,  2.58576365,  2.6073872 ,
         2.02427681,  1.9072407 ,  1.4997171 ,  9.08167828,  4.67035982]])

In [30]:
np.random.normal(0,1,(4,5))

array([[ 2.06519892,  0.52342126, -0.06666019, -0.24721749,  2.99315535],
       [ 2.24928642, -0.19231639,  1.65280474, -2.19181736,  0.03137508],
       [-0.73053114,  0.29956182, -0.33756541,  0.59318701, -2.41557046],
       [ 1.60347797, -0.13740694,  0.04071609,  0.24906117, -0.2460625 ]])

In [31]:
np.random.randint(50,100,30)

array([84, 83, 69, 96, 56, 83, 98, 52, 95, 98, 70, 89, 80, 61, 71, 60, 56,
       71, 74, 71, 77, 93, 53, 89, 53, 94, 55, 64, 91, 97])

In [230]:
arr9 = np.random.randint(10,101,(20,2))
arr9

array([[51, 78],
       [78, 93],
       [17, 36],
       [39, 11],
       [99, 97],
       [27, 53],
       [65, 67],
       [46, 89],
       [36, 30],
       [76, 67],
       [73, 32],
       [62, 64],
       [77, 10],
       [78, 82],
       [88, 10],
       [24, 12],
       [13, 73],
       [26, 13],
       [72, 91],
       [93, 44]])

In [33]:
arr9.ndim 

2

In [34]:
arr9.size 

40

In [35]:
arr9.shape 

(20, 2)

In [36]:
arr9.dtype 

dtype('int32')

In [37]:
np.random.seed(101)
ar = np.random.randint(1,10,10)
ar

array([2, 7, 8, 9, 5, 9, 6, 1, 6, 9])

In [38]:
ar[:4]

array([2, 7, 8, 9])

In [39]:
ar[-1]

9

In [40]:
ar[5]

9

In [41]:
ar[1]=45
ar

array([ 2, 45,  8,  9,  5,  9,  6,  1,  6,  9])

In [42]:
np.random.seed(100)
arr0 = np.arange(0,25).reshape(5,5)
arr0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr0[0:3,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [44]:
arr0[0,1]

1

In [45]:
arr0[0:3,1]

array([ 1,  6, 11])

In [46]:
arr0[:3,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [47]:
arr0[2::-1,3::-1]

array([[13, 12, 11, 10],
       [ 8,  7,  6,  5],
       [ 3,  2,  1,  0]])

In [48]:
arr0[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [49]:
arr0[2::2,3::2]

array([[13],
       [23]])

In [50]:
arr0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
ar0 = arr0[2:5,2:5]
ar0

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [52]:
ar0[2,2]=122
ar0

array([[ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23, 122]])

In [53]:
arr0 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23, 122]])

In [54]:
ar1 = arr0[2:5,2:5].copy()
ar1

array([[ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23, 122]])

In [55]:
ar1[2,2]=24
ar1

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [56]:
arr0 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23, 122]])

In [57]:
arrrr = np.arange(3)
arrrr.reshape(3,1)


array([[0],
       [1],
       [2]])

In [58]:
arrrr = np.arange(16)
reshape = arrrr.reshape(4,4)  
reshape.reshape(1,16)   

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [59]:

ar.ravel?
reshape.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [60]:
flatten = reshape.flatten()

In [61]:
flatten[:,np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [62]:
np.concatenate([ar0,ar1])  

array([[ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23, 122],
       [ 12,  13,  14],
       [ 17,  18,  19],
       [ 22,  23,  24]])

In [63]:
np.concatenate([ar0,ar1],axis=1)  

array([[ 12,  13,  14,  12,  13,  14],
       [ 17,  18,  19,  17,  18,  19],
       [ 22,  23, 122,  22,  23,  24]])

In [64]:
ar3=np.array([1,2,3,4,5,6]).reshape(2,3)
ar3

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
ar4=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
ar4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
np.concatenate([ar3,ar4],axis=1)

array([[1, 2, 3, 1, 2, 3, 4],
       [4, 5, 6, 5, 6, 7, 8]])

In [67]:
x=np.array([[1,2,3],[4,5,6]])
arrrrr = np.array([7,8,9])
ar90 = np.array([[1,2],[3,4]])
ar09 = np.array((1,2,3,4,5))

In [68]:
np.vstack([x,arrrrr])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
np.vstack([arrrrr,x])

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
np.hstack([x,ar90])

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])

In [71]:
x
ar89 = np.array((1,2,3,4,5,6))

In [72]:
np.split(ar89,(1,4,5),axis=0) 

[array([1]), array([2, 3, 4]), array([5]), array([6])]

In [73]:
np.vsplit(x,[1,2])

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

In [74]:
np.hsplit(x,[2,2])
# it return [:1],[1:2],[2:]

[array([[1, 2],
        [4, 5]]),
 array([], shape=(2, 0), dtype=int32),
 array([[3],
        [6]])]

In [75]:
ar101 = np.array([[1,2,3],[-4,5,6],[7,-8,9]])
np.sum(ar101)

21

In [76]:
np.sum(ar101,axis=1)

array([6, 7, 8])

In [77]:
np.sum(ar101,axis=0)

array([ 4, -1, 18])

In [78]:
np.std(ar101)

5.120763831912405

In [79]:
np.prod(ar101)

362880

In [80]:
np.var(ar101)

26.222222222222218

In [81]:
np.abs(ar101)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.argmax(ar101)

8

In [83]:
np.argmin(ar101)

7

In [84]:
np.argmax(ar101,axis=0)

array([2, 1, 2], dtype=int64)

In [85]:
np.argmin(ar101,axis=0)

array([1, 2, 0], dtype=int64)

In [86]:
np.argmax(ar101,axis=1)

array([2, 2, 2], dtype=int64)

In [87]:
np.argmin(ar101,axis=1)

array([0, 0, 1], dtype=int64)

In [88]:
np.median(ar101)

3.0

In [89]:
# np.all?
np.all(ar101,axis=0)

array([ True,  True,  True])

In [90]:
ar401=np.array([1,2,3,4])
ar401

array([1, 2, 3, 4])

In [91]:
ar401>2

array([False, False,  True,  True])

In [92]:
ar401==2

array([False,  True, False, False])

In [93]:
ar401<6

array([ True,  True,  True,  True])

In [94]:
ar401!=9

array([ True,  True,  True,  True])

In [95]:
import numpy as np

In [96]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [97]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [98]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [99]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [100]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
a=np.eye(3,3)
a
np.all(a)

False

In [102]:
np.random.randint(0,2,1)


array([0])

In [103]:
np.random.standard_normal(25)


array([-0.89325872,  1.7382604 , -1.17970327,  0.08857118, -0.36377559,
       -0.39830003, -0.23471518, -1.43973704,  0.4328165 ,  2.30447259,
       -0.12263538,  0.01545931,  0.26601635, -0.11379467,  1.01106614,
       -1.44077118,  0.98056914,  1.37699631, -0.23028509,  0.48092412,
       -1.26691058,  0.27100509,  2.14076322,  0.47536904,  0.24652489])

In [104]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [105]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [106]:
ar1001 = np.array([[ 1,  2,  3,  4,  5], 
       [ 6,  7,  8,  9, 10], 
       [11, 12, 13, 14, 15], 
       [16, 17, 18, 19, 20], 
       [21, 22, 23, 24, 25]]) 
ar1001

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [107]:

ar1001[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [108]:
ar1001[3:4,-1]

array([20])

In [109]:
ar1001[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [110]:
ar1001[4]

array([21, 22, 23, 24, 25])

In [111]:
ar1001[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [112]:
np.sum(ar1001)

325

In [113]:
np.sum(ar1001,axis=0)

array([55, 60, 65, 70, 75])

In [114]:
np.std(ar1001,axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [115]:
np.var(ar1001,axis=1)

array([2., 2., 2., 2., 2.])

In [116]:
np.min(ar1001,axis=1)

array([ 1,  6, 11, 16, 21])

In [117]:
np.max(ar1001,axis=1)

array([ 5, 10, 15, 20, 25])

In [118]:
a = np.full((6,6),np.nan)
a[1:5,1:5]=1
a


array([[nan, nan, nan, nan, nan, nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan, nan, nan, nan, nan, nan]])

##  EXERCISE 2

In [119]:
ar1=np.array([2,3,4,5])
ar1

array([2, 3, 4, 5])

In [120]:
np.random.seed(1)
ar2=np.arange(0,9).reshape(3,3)
ar2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [121]:
np.random.seed(2)
ar3=np.arange(0,27).reshape(3,3,3)
ar3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [122]:
ar3.dtype

dtype('int32')

In [123]:
ar1.shape 

(4,)

In [124]:
ar2.shape

(3, 3)

In [125]:
ar3.shape

(3, 3, 3)

In [126]:
ar1.ndim

1

In [127]:
ar2.ndim

2

In [128]:
ar3.ndim

3

In [129]:
ar4 = np.zeros(12)
ar4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [130]:
ar5 = np.ones((2,10))
ar5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [131]:
np.random.seed(102)
Maths_Marks = np.random.randint(0,100,20)
Maths_Marks

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7,  4, 38, 82, 55,  3, 96,  0,
       80, 71, 25])

In [132]:
desc = np.sort(Maths_Marks)[::-1]  
desc

array([96, 82, 80, 79, 78, 73, 73, 72, 72, 71, 66, 55, 45, 38, 25,  7,  4,
        3,  0,  0])

In [133]:
asc = np.sort(Maths_Marks)  
asc

array([ 0,  0,  3,  4,  7, 25, 38, 45, 55, 66, 71, 72, 72, 73, 73, 78, 79,
       80, 82, 96])

In [134]:
copy_dsc = np.copy(desc)
copy_dsc

array([96, 82, 80, 79, 78, 73, 73, 72, 72, 71, 66, 55, 45, 38, 25,  7,  4,
        3,  0,  0])

In [135]:
ar10001 = np.eye(5,5)

In [136]:
np.reshape(ar10001,(1,25))

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1.]])

In [137]:
np.random.seed(10000)
ar201 = np.random.randint(0,9,9).reshape(3,3)
ar201


array([[5, 8, 2],
       [5, 8, 1],
       [6, 8, 5]])

In [138]:
np.random.seed(10001)
ar202 = np.random.randint(0,9,3)
ar202

array([1, 4, 6])

In [139]:
ar301 = np.vstack((ar201,ar202))
ar301

array([[5, 8, 2],
       [5, 8, 1],
       [6, 8, 5],
       [1, 4, 6]])

In [140]:

np.vsplit(ar301,[2,3])


[array([[5, 8, 2],
        [5, 8, 1]]),
 array([[6, 8, 5]]),
 array([[1, 4, 6]])]

In [141]:
np.hsplit(ar301,[1,2])

[array([[5],
        [5],
        [6],
        [1]]),
 array([[8],
        [8],
        [8],
        [4]]),
 array([[2],
        [1],
        [5],
        [6]])]

In [142]:
np.eye(4,4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [143]:
ar302 = np.array([1.2,6.5,8.0,7.7,3.4,1.9])
np.ceil(ar302)

array([2., 7., 8., 8., 4., 2.])

In [144]:
np.floor(ar302)

array([1., 6., 8., 7., 3., 1.])

In [145]:
np.round(ar302)

array([1., 6., 8., 8., 3., 2.])

In [146]:
ar303 = np.arange(3,28).reshape(5,5)

In [147]:
np.min(ar303,axis=0)

array([3, 4, 5, 6, 7])

In [148]:
np.max(ar303,axis=0)

array([23, 24, 25, 26, 27])

In [149]:
np.var(ar303,axis=0)

array([50., 50., 50., 50., 50.])

In [150]:
np.std(ar303,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [151]:
nv = np.full(10,np.nan)
nv[6]=200
nv


array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [152]:
vec1 = np.arange(100,151)
vec1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [153]:
vec1[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [154]:
np.arange(0,25).reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [155]:
ar403 = np.array([1,0,2,0,0,4,0,8])
np.nonzero(ar403)[0]

array([0, 2, 5, 7], dtype=int64)

In [156]:
ar404 = np.full(100,1).reshape(10,10)
ar404[1:9,1:9]=0
ar404

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [189]:
mat1 = np.ones((9,9))
mat1[::2,::2]=0
mat1[1::,1::2]=0
mat1

array([[0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [158]:
np.random.seed(1002)
ar405 = np.random.randint(0,9,9).reshape(3,3)
ar405

array([[7, 1, 8],
       [8, 4, 0],
       [5, 5, 2]])

In [159]:
np.random.seed(20001)
ar406 = np.random.randint(20,50,9).reshape(3,3)
ar406

array([[25, 29, 26],
       [43, 25, 29],
       [31, 41, 43]])

In [160]:
np.sum((ar405,ar406),axis=0)

array([[32, 30, 34],
       [51, 29, 29],
       [36, 46, 45]])

In [161]:
np.multiply(ar405,ar406)

array([[175,  29, 208],
       [344, 100,   0],
       [155, 205,  86]])

In [162]:
np.subtract(ar406,ar405)

array([[18, 28, 18],
       [35, 21, 29],
       [26, 36, 41]])