In [32]:
import numpy as np

In [33]:
a=np.ones((10,10))

In [34]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
a[1:9,1:9]=2

In [39]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
a[2:8,2:8]=3

In [41]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
a[3:7,3:7]=4

In [43]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
a[4:6,4:6]=5

In [49]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 4., 5., 5., 4., 3., 2., 1.],
       [1., 2., 3., 4., 5., 5., 4., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])