In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.2.2'

In [3]:
pd.Series?

Init signature:
pd.Series(
    data=None,
    index=None,
    dtype: 'Dtype | None' = None,
    name=None,
    copy: 'bool | None' = None,
    fastpath: 'bool | lib.NoDefault' = <no_default>,
) -> 'None'
Docstring:     
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, \*, \*\*) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

Parameters
----------
data : array-like, Iterable, dict, or scalar value
    Contains data stored in Series. If data is a dict, argument order is
    maintained.
index : array-like or Index (1d)
    

In [4]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [5]:
d = {'a': 1, 'b': 2, 'c': 3}
s= pd.Series(d)

In [6]:
s

a    1
b    2
c    3
dtype: int64

In [7]:
a= [99,99,99,99,99]
x=pd.Series(index=["Math","Data Science","Calculus","Descrite","Tablue"],copy=False, data=a)

In [8]:
display(x,x.values,x.index,)

Math            99
Data Science    99
Calculus        99
Descrite        99
Tablue          99
dtype: int64

array([99, 99, 99, 99, 99], dtype=int64)

Index(['Math', 'Data Science', 'Calculus', 'Descrite', 'Tablue'], dtype='object')

In [9]:
x["math"]=1
a


[99, 99, 99, 99, 99]

In [10]:
d={"Kishan":"A+++++","Sam":"A","Rudra":"A-"}
z=pd.Series(d)

In [11]:
z

Kishan    A+++++
Sam            A
Rudra         A-
dtype: object

In [12]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [13]:
pd.DataFrame({'Riya':[90,90],'Mia':[99,99]},index=["Py",'Ex'])

Riya  Mia
Py    90   99
Ex    90   99

In [14]:
pd.DataFrame([[80,99],[99,88]],index=['Riya','Mia'],columns=['py','R'])

py   R
Riya  80  99
Mia   99  88

In [15]:
np.random.seed(10)
df=pd.DataFrame(np.random.randint(80,99,(3,3)),index=['KK',"SS","RR"],columns=["Py","C++","Aws"])

In [16]:
df.columns

Index(['Py', 'C++', 'Aws'], dtype='object')

In [17]:
df.values

array([[89, 84, 95],
       [80, 97, 96],
       [97, 88, 89]])

In [18]:
df.index

Index(['KK', 'SS', 'RR'], dtype='object')

In [19]:
df[['Py', 'C++']]

Py  C++
KK  89   84
SS  80   97
RR  97   88

In [20]:
df["Total"]=df["Py"]+df["C++"]+df["Aws"]

In [21]:
df["Percent"]=df["Total"]/3

In [22]:
df.loc['KK']

Py          89.000000
C++         84.000000
Aws         95.000000
Total      268.000000
Percent     89.333333
Name: KK, dtype: float64

In [23]:
df["Py"].iloc[:]

KK    89
SS    80
RR    97
Name: Py, dtype: int32

In [24]:
df.loc[:"SS","C++":"Total"]

C++  Aws  Total
KK   84   95    268
SS   97   96    273

In [25]:
df.iloc[:,-3]

KK    95
SS    96
RR    89
Name: Aws, dtype: int32

In [26]:
df[df.Py>88][:1]

Py  C++  Aws  Total    Percent
KK  89   84   95    268  89.333333

In [27]:
m={"Name":["A","B","C","D"],"Math":[35,11,44,55],"Science":[44,40,55,88],"Physics":[99,11,44,87]}
df=pd.DataFrame(m)

In [28]:
df

Name  Math  Science  Physics
0    A    35       44       99
1    B    11       40       11
2    C    44       55       44
3    D    55       88       87

In [29]:
df[df.loc[:,"Math":"Math"]<40]=41

In [30]:
df

Name  Math  Science  Physics
0    A    41       44       99
1    B    41       40       11
2    C    44       55       44
3    D    55       88       87

In [31]:
df.loc[:,"Math":"Math"]<40

Math
0  False
1  False
2  False
3  False

In [44]:
S = pd.Series([10, 20, 30, 40])
S.values

array([10, 20, 30, 40], dtype=int64)

In [45]:
S.index

RangeIndex(start=0, stop=4, step=1)

In [46]:
 S[2]

30

In [47]:
 S[0:3]

0    10
1    20
2    30
dtype: int64

In [49]:
S.index = ['a', 'b', 'c', 'd']

In [51]:
S['b'] = 50
S

a    10
b    50
c    30
d    40
dtype: int64

In [37]:
P = pd.Series({'Delhi': 1, 'Jaipur': 2, 'Chennai': 3, 'Surat': 4, 'Agra': 5})

In [54]:
 P['Delhi']

1

In [55]:
 P[1:4]

Jaipur     2
Chennai    3
Surat      4
dtype: int64

In [39]:
data = {'Column1': [1, 2, 3, 4], 'Column2': [10, 20, 30, 40]}
df = pd.DataFrame(data)

In [56]:
 df['Column2']

0    10
1    20
2    30
3    40
Name: Column2, dtype: int64

In [57]:
 df.iloc[1]

Column1      2
Column2     20
Column3    200
Name: 1, dtype: int64

In [59]:
df['Column3'] = [100, 200, 300, 400]

df.drop(index=2)

Column1  Column2  Column3
0        1       10      100
1        2       20      200
3        4       40      400